services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Mousset\ClassificationstoreBundle\Command\ClassificationstoreImportCommand: ~
    Mousset\ClassificationstoreBundle\Command\ClassificationstoreExportCommand: ~

    Mousset\ClassificationstoreBundle\Import\Interfaces\ItemFactoryInterface:
        class: Mousset\ClassificationstoreBundle\Import\ItemFactory

    Mousset\ClassificationstoreBundle\Import\Interfaces\KeyFactoryInterface:
        class: Mousset\ClassificationstoreBundle\Import\KeyFactory

    Mousset\ClassificationstoreBundle\Import\Importer:
        public: true

    Mousset\ClassificationstoreBundle\Export\Interfaces\ItemFactoryInterface:
      class: Mousset\ClassificationstoreBundle\Export\ItemFactory

    Mousset\ClassificationstoreBundle\Export\Interfaces\KeyFactoryInterface:
      class: Mousset\ClassificationstoreBundle\Export\KeyFactory

    Mousset\ClassificationstoreBundle\Export\Exporter:
        public: true

    Mousset\ClassificationstoreBundle\Repository\StoreRepository:
        public: true

    Mousset\ClassificationstoreBundle\Repository\CollectionRepository:
        public: true

    Mousset\ClassificationstoreBundle\Repository\GroupRepository:
        public: true

    Mousset\ClassificationstoreBundle\Repository\KeyRepository:
        public: true

    Mousset\ClassificationstoreBundle\Component\FieldWrapperInterface:
        class: Mousset\ClassificationstoreBundle\Component\FieldWrapper
        public: true

    Mousset\ClassificationstoreBundle\Export\Item\Store:
        public: true

    Mousset\ClassificationstoreBundle\Export\Item\Collection:
        public: true

    Mousset\ClassificationstoreBundle\Export\Item\Group:
        public: true

    Mousset\ClassificationstoreBundle\Export\Item\Key:
        public: true
